# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then call a random question with `pick()` an hint towards its solution with
`hint(n)` and the answer with `answer(n)`, where n is the number of the picked question.

In [65]:
import os
print(os.getcwd())

d:\CODE\ds2\test\numpy-100


In [67]:
cur_dir = os.getcwd()
os.chdir(cur_dir + '/../test/numpy-100/')
print(os.getcwd())

FileNotFoundError: [WinError 3] 지정된 경로를 찾을 수 없습니다: 'd:\\CODE\\ds2\\test\\numpy-100/../test/numpy-100/'

In [64]:
%run initialise.py

In [68]:
pick()

18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)


In [72]:
import numpy as np
np.eye((5, 5))

TypeError: 'tuple' object cannot be interpreted as an integer

In [73]:
hint(18)

hint: np.diag


In [75]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [76]:
np.diag([1, 2, 3, 4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [77]:
answer(18)

Z = np.diag(1+np.arange(4),k=-1)
print(Z)


In [78]:
np.diag(1+np.arange(4), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [79]:
help(np.diag)

Help on _ArrayFunctionDispatcher in module numpy:

diag(v, k=0)
    Extract a diagonal or construct a diagonal array.
    
    See the more detailed documentation for ``numpy.diagonal`` if you use this
    function to extract a diagonal and wish to write to the resulting array;
    whether it returns a copy or a view depends on what version of numpy you
    are using.
    
    Parameters
    ----------
    v : array_like
        If `v` is a 2-D array, return a copy of its `k`-th diagonal.
        If `v` is a 1-D array, return a 2-D array with `v` on the `k`-th
        diagonal.
    k : int, optional
        Diagonal in question. The default is 0. Use `k>0` for diagonals
        above the main diagonal, and `k<0` for diagonals below the main
        diagonal.
    
    Returns
    -------
    out : ndarray
        The extracted diagonal or constructed diagonal array.
    
    See Also
    --------
    diagonal : Return specified diagonals.
    diagflat : Create a 2-D array with the flatt

In [80]:
pick()

22. Normalize a 5x5 random matrix (★☆☆)


In [81]:
hint(22)

hint: (x -mean)/std


In [83]:
a = np.random.normal()
a

-1.1973491296264078

In [84]:
answer(22)

Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)


In [85]:
np.random.random((5, 5))

array([[0.60894674, 0.70335661, 0.50504304, 0.96303108, 0.7299445 ],
       [0.91998875, 0.86144193, 0.11843893, 0.62651673, 0.30780464],
       [0.43944718, 0.23421977, 0.99377594, 0.04006199, 0.28027717],
       [0.40335288, 0.87579231, 0.52198243, 0.24268798, 0.98313234],
       [0.43406097, 0.27593306, 0.1191312 , 0.1746887 , 0.76275241]])

In [86]:
A = np.random.random((5, 5))
A = (A - np.mean(A)) / np.std(A)
print(A)

[[ 1.44712592e+00  8.17386481e-01  4.30221643e-01  1.03800431e+00
  -1.32001276e+00]
 [ 1.55056915e+00  1.07406221e+00 -1.38830097e+00  2.76119407e-01
  -4.52349661e-01]
 [ 4.53665541e-01 -5.89399295e-01 -1.10988854e-03  8.13651971e-01
   1.34601084e+00]
 [ 1.30610946e+00 -1.44364503e+00  4.06215819e-01 -4.60243304e-01
   7.21697323e-02]
 [-1.43987963e+00 -1.21210571e+00 -1.19375438e+00 -5.11464984e-01
  -1.01904688e+00]]
